### 
http://localhost/ppe1820/bornes.php

### fonctionne 
GET http://localhost/ppe1820/photos.php?code=EFFICOM

###
POST http://localhost/ppe1820/likes.php 
Content-Type: application/x-www-form-urlencoded
photo_id=1

# fichier en prod
###
https://duplessigeoffrey.fr/api2/photos_event.php?code=SONA

POST https//duplessigeoffrey.fr/api2/like.php
Content-Type: application/x-www-form-urlencoded

photo_id=3
###
POST http://localhost/ppe1820/duplessigeoffrey.fr/api2/login_mobile.php
Content-Type: application/x-www-form-urlencoded

nickname=tata&password=tata

###
POST http://localhost/ppe1820/like.php 
Content-Type: application/x-www-form-urlencoded

photo_id=1&token=

### fonctionne(oui) erreur 401 si erreur token n'est pas valide 
POST http://localhost/ppe1820/like.php 
Content-Type: application/x-www-form-urlencoded

photo_id=6&token=b8Wm0phnNclidYMd2zXRs62jhftMRAfUcB8IrVmyaV

### fonctionne bien  - Affiche la liste des bornes ppour l'evenement
GET http://localhost/ppe1820/photos.php?code=efficom

### fonctionne bien - retunr un token
POST http://localhost/ppe1820/login_mobile.php
Content-Type: application/x-www-form-urlencoded

nickname=tata&password=tata

### 
POST http